### PR TITLE
migration to new version of clarifai-python-SDK

### PR DESCRIPTION
**Pull request by mogith-pn**
https://clarifai.atlassian.net/browse/TT-2960

### CODE REVIEW

**Review by sainivedh — COMMENTED** [review]
Looks Good. Noticed some indentation issues, you could use a [pre-commit config](https://clarifai.atlassian.net/wiki/spaces/EN/pages/1908738912/Setting+up+a+development+environment#Git-pre-commit-hooks) to do all lint/format fixes.

**Comment by mogith-pn** [comment]
> Looks Good. Noticed some indentation issues, you could use a [pre-commit config](https://clarifai.atlassian.net/wiki/spaces/EN/pages/1908738912/Setting+up+a+development+environment#Git-pre-commit-hooks) to do all lint/format fixes.

Please check now and let me know.

**Comment by sainivedh** [comment]
> > Looks Good. Noticed some indentation issues, you could use a [pre-commit config](https://clarifai.atlassian.net/wiki/spaces/EN/pages/1908738912/Setting+up+a+development+environment#Git-pre-commit-hooks) to do all lint/format fixes.
> 
> Please check now and let me know.

You could add a [pre-commit](https://github.com/Clarifai/module-manager/blob/main/.pre-commit-config.yaml) file as rest of the modules and run the config. This helps in improving readability and maintainability

**Review by sainivedh — APPROVED** [review]
lgtm

**Pull request merged**
